# Generated by Django 4.1.6 on 2023-02-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrainNum', models.PositiveIntegerField()),
                ('OrgCity', models.CharField(max_length=200)),
                ('DesCity', models.CharField(max_length=200)),
                ('TrainFare', models.PositiveIntegerField()),
            ],
        ),
    ]
